version: '3'

services:
   webserver:
       image: pythonflask:latest
       ports:
       - "5000:5000"
       command: sh -c "cd /home/servidorFlask && FLASK_APP=main.py flask run --host=0.0.0.0"
       deploy:
            resources:
              limits:
                cpus: '0.001'
                memory: 50M
              reservations:
                memory: 20M